baseurl: "/BaroEconomy"
exclude: [README.md]
defaults:
  - scope:
      path: "" # All files
    values:
      version: "0-21-6-0" # Most recent Barotrauma version
  - scope:
      path: "**.html"
    values:
      layout: "default"
      lang: "en"
      author: "Matthew Eppel"
      scripts: []
      # style: <name>
