exclude: [README.md]
defaults:
  - scope:
      path: "" # all files
    values:
      layout: "default"
      lang: "en"
      author: "Matthew Eppel"
      scripts: []
      version: 0.20.15.0 # Most recent Barotrauma version
      # style: <name>