baseurl: "/StorageTrauma"
exclude: [README.md]
defaults:
  - scope:
      path: "" # All files
    values:
      version: "1-6-17-0" # Most recent Barotrauma version
  - scope:
      path: "**.html"
    values:
      layout: "default"
      lang: "en"
      author: "Matthew Eppel"
      scripts: []
      # style: <name>
